name: Python CI

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main  # Change this to your main branch
  # pull_request:
  #   branches:
  #     - main  # Change this to your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    # - name: Cache Python dependencies
    #   uses: actions/cache@v2
    #   with:
    #     path: ~/.cache/pip
    #     key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
    #     restore-keys: |
    #       ${{ runner.os }}-pip-
    #   if: runner.os != 'Windows'

    # - name: Install Python dependencies
    #   run: pip install -r requirements.txt

    - name: Set Environment Variable
      run: |
        echo "RUN_ID=${{ github.run_id }}" >> $GITHUB_ENV
        
    - name: Run tests
      run: |
        python test.py
      working-directory: ./src
      
    - name: Export excel file path
      run: |
        filename="./src/$RUN_ID.txt"
        echo "Uploading $filename as an artifact"
        echo "artifact_path=$filename" >> $GITHUB_OUTPUT
      id: excel-file-path
        
    - name: Upload Excel as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: generated-excel
        path: ${{ steps.excel-file-path.outputs.artifact_path }}
